### ISSUE TITLE
Google signin 

### ISSUE THREAD

**Issue by nikhilreddy123456** [myflashlab/GoogleSignIn-ANE#16] opened 2018-09-07 10:16 UTC
Hi,
 There are two links for  GoogleSignIn ANE V1.2.0 for Android+iOS and Google Game Services ANE V4.0.0 for Android  which is the latest version want to use for google signIn and please provide latest coding for developing.

**Comment by myflashlab** [comment] 2018-09-07 12:31
Please send us a link to your app to check it out.

**Comment by nikhilreddy123456** [comment] 2018-09-10 04:04
Hi,
 The app is in Alpha testing so there is no link to send for you.

**Comment by nikhilreddy123456** [comment] 2018-09-10 09:42
Hi,

![ipmsgclip_s_1536572489_0](https://user-images.githubusercontent.com/39688242/45289926-f38a6080-b50b-11e8-96b6-b98b84430a3b.png)

**Comment by nikhilreddy123456** [comment] 2018-09-10 13:17
Hi,

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3313)
  at android.app.ActivityThread.-wrap17 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1742)
  at android.os.Handler.dispatchMessage (Handler.java:108)
  at android.os.Looper.loop (Looper.java:206)
  at android.app.ActivityThread.main (ActivityThread.java:6735)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:845)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:93)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3308)

**Comment by myflashlab** [comment] 2018-09-10 14:34
Ok, this is now more clear. As seen in the error log, the problem is NOT directly related to ANEs. The problem is generally with using ANEs as general speaking. This topic has been discussed a lot on Adobe forums and I'm sure you can find them easily with a little Googling. For more details you may check this link also: https://stackoverflow.com/questions/43435658/didnt-find-class-on-path-dexpathlist

So, the problem is with multidexing. While making sure that you are using the latest version of AdobeAIR SDK, add ```android:name="android.support.multidex.MultiDexApplication" ``` to your Android ```<application``` tag as an attribute.

I'm closing the issue now because the question is not directly related to ANEs.

**Closed by myflashlab** 2018-09-10 14:34 UTC

**Comment by nikhilreddy123456** [comment] 2018-09-11 04:31
<android>
     <manifestAdditions><![CDATA[<manifest android:installLocation="auto">


<uses-sdk android:targetSdkVersion="27"/>
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
<uses-permission android:name="android.permission.USE_CREDENTIALS" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="com.android.vending.BILLING" />
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>

<application android:name="android.support.multidex.MultiDexApplication">

		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
		
		
        <activity
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />
			
		
		<activity android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:excludeFromRecents="true" android:exported="false"/>
		<service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService" android:exported="true" android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>
		<activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false"/>
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
			
								
		 <receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver" android:enabled="true">					 
		<intent-filter>						
		 <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />					
		 </intent-filter>				
		 </receiver>	
		 
		 <service android:name="com.google.android.gms.analytics.AnalyticsService" android:enabled="true" android:exported="false"/>				
						
		<service android:name="com.google.android.gms.analytics.CampaignTrackingService" />				
		<receiver android:name="com.milkmangames.extensions.android.ganalytics.CampaignTrackingReceiver" android:exported="true">				
		  <intent-filter>					
		<action android:name="com.android.vending.INSTALL_REFERRER" />				
		  </intent-filter>				
		</receiver>  
		  </application>
</manifest>]]></manifestAdditions>
</android>

**Comment by nikhilreddy123456** [comment] 2018-09-11 04:34
<android>
     <manifestAdditions><![CDATA[<manifest android:installLocation="auto">


<uses-sdk android:targetSdkVersion="27"/>
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
<uses-permission android:name="android.permission.USE_CREDENTIALS" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="com.android.vending.BILLING" />
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>

<application android:name="android.support.multidex.MultiDexApplication">

		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
		
		
        <activity
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />
			
		
		<activity android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:excludeFromRecents="true" android:exported="false"/>
		<service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService" android:exported="true" android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>
		<activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false"/>
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
			
								
		 <receiver android:name="com.google.android.gms.analytics.AnalyticsReceiver" android:enabled="true">					 
		<intent-filter>						
		 <action android:name="com.google.android.gms.analytics.ANALYTICS_DISPATCH" />					
		 </intent-filter>				
		 </receiver>	
		 
		 <service android:name="com.google.android.gms.analytics.AnalyticsService" android:enabled="true" android:exported="false"/>				
						
		<service android:name="com.google.android.gms.analytics.CampaignTrackingService" />				
		<receiver android:name="com.milkmangames.extensions.android.ganalytics.CampaignTrackingReceiver" android:exported="true">				
		  <intent-filter>					
		<action android:name="com.android.vending.INSTALL_REFERRER" />				
		  </intent-filter>				
		</receiver>  
		  </application>
</manifest>]]></manifestAdditions>
</android>
