### ISSUE TITLE
Build IOS fail with "duplicate symbols for architecture"

### ISSUE THREAD

**Issue by sangph** [myflashlab/GoogleSignIn-ANE#19] opened 2018-10-05 10:34 UTC
## Environment ##
* Android Version:
* iOS Version: 
* AIR Version: 30

## Problem Description ##
Hi, 
I got a problem when I build App on IOS. Please review short manifest .xml file. 
If I lock comment <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>  ==> build OK
But I unlock comment <extensionID>com.myflashlab.air.extensions.google.signin</extensionID> ==> get error: 
> duplicate symbol _OBJC_CLASS_$_GTMLogStandardFormatter in:
>     D:\\Software\\AIR_SDK_30\\lib\\aot/stub/GoogleToolboxForMac.framework/GoogleToolboxForMac(GTMLogger.o)
>     D:\\Software\\AIR_SDK_30\\lib\\aot/stub/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMLogger_fd76b46e561d4433aab1e0875958b7b8.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogStandardFormatter in:
    D:\\Software\\AIR_SDK_30\\lib\\aot/stub/GoogleToolboxForMac.framework/GoogleToolboxForMac(GTMLogger.o)
    D:\\Software\\AIR_SDK_30\\lib\\aot/stub/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMLogger_fd76b46e561d4433aab1e0875958b7b8.o)
duplicate symbol _OBJC_CLASS_$_GTMLogBasicFormatter in:
    D:\\Software\\AIR_SDK_30\\lib\\aot/stub/GoogleToolboxForMac.framework/GoogleToolboxForMac(GTMLogger.o)
    D:\\Software\\AIR_SDK_30\\lib\\aot/stub/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMLogger_fd76b46e561d4433aab1e0875958b7b8.o)
duplicate symbol _OBJC_METACLASS_$_GTMLogBasicFormatter in:
    D:\\Software\\AIR_SDK_30\\lib\\aot/stub/GoogleToolboxForMac.framework/GoogleToolboxForMac(GTMLogger.o)
    D:\\Software\\AIR_SDK_30\\lib\\aot/stub/GoogleSignInDependencies.framework/GoogleSignInDependencies(GTMLogger_fd76b46e561d4433aab1e0875958b7b8.o)
.....
ld: 26 duplicate symbols for architecture armv7

Please help me. Thanks so much any feedback. 

```xml
<extensions>				
		<!--<extensionID>com.myflashlab.air.extensions.google.signin</extensionID>-->
		<extensionID>com.myflashlab.air.extensions.fileBrowser</extensionID>		
		<extensionID>com.myflashlab.air.extensions.facebook</extensionID>
		<extensionID>com.myflashlab.air.extensions.billing</extensionID>
		
		
		<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
		<extensionID>com.myflashlab.air.extensions.firebase.analytics</extensionID>
		<extensionID>com.myflashlab.air.extensions.firebase.remoteConfig</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.config</extensionID>		
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
		<extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
		<extensionID>com.myflashlab.air.extensions.firebase.crashlytics</extensionID>		
		
        <extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>			
		<extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>        
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
		
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>	
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>		
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
				
	</extensions>
```
```actionscript
Copy your Actionscript code.
```

## Known Workarounds ##

**Comment by myflashlab** [comment] 2018-10-09 12:43
The error log you have posted shows duplicated symbol problem in the framework files. My first guess is that you have forgotten to update your framework files. So, make sure you are using the latest version of ANEs and also copy the frameworks which are linked for Firebase and GoogleSignIn.

**Comment by myflashlab** [comment] 2018-10-11 10:04
Ok, this seems like a problem that even native devs are facing! We're working on a fix now. The problem is that the GoogleSignIn is using ```GoogleSignInDependencies.framework``` which is actually a bundle of other dependencies which are already found in Firebase frameworks. 

@sangph and @Parkdaejoon Please let me know if you are using ANELAB for your project? if yes, we can send you test ANEs to use inside ANELAB and see if the problem will be fixed for you...?

**Comment by Parkdaejoon** [comment] 2018-10-11 10:12
A month ago, I registered a paid member for a year. All of the Jane files are paid files and I don't think we should upload them here. If you let me know your email, I will send it to you.

**Comment by myflashlab** [comment] 2018-10-11 10:14
No, *I* will send a fixed ANE to you. I am asking if you are using ANELAB software? because it will be easier to test with ANELAB.

**Comment by Parkdaejoon** [comment] 2018-10-11 10:15
"ANELAB software" i don't understand
i'm flash animate use

**Comment by myflashlab** [comment] 2018-10-11 10:18
Ok, then, you don't use it then :smile: On your spare time, consider using [this ANELAB](https://github.com/myflashlab/ANE-LAB). This is accessible for Myflashlabs Club members only.

Anyway, for this current ```duplicate symbol``` problem, please hold on while we are finishing our tests... I'll send you the instruction to see if the problem is fixed or not.

**Comment by Parkdaejoon** [comment] 2018-10-11 10:21
After joining the membership for one year, we installed the ANE LAB, not the Korean version;;;

**Comment by myflashlab** [comment] 2018-10-11 10:40
Ok, here's the manual instruction considering that you have already setup your project manually.

**Source of the problem:**
the framework **GoogleSignInDependencies.framework** holds other frameworks which are seperated in Firebase builds. Google should have fixed this. but anyhow, please let us know if this works for you so we can release the commercial version as soon as possible. 

1. download [V5.4.1](https://dl.google.com/firebase/sdk/ios/5_4_1/Firebase-5.4.1.zip) of Firebase SDK for iOS. *This is the version we are using in Firebase ANEs V7.0.0
2. Extract the zip file and copy the following framework files to your AIR SDK ```AIR/lib/aot/stub```
    * Invites/GTMSessionFetcher.framework
    * Invites/GTMOAuth2.framework
3. Now remove/delete the framework **GoogleSignInDependencies.framework** from ```AIR/lib/aot/stub```.
4. Replace the old GoogleSignIn ANE you have with this test version here: [googleSignIn.ane.zip](https://github.com/myflashlab/GoogleSignIn-ANE/files/2468545/googleSignIn.ane.zip)

Now run your project and you will not see that error message again. Yet, test and make sure the new GoogleSignIn ANE is functioning all correctly?

**Comment by myflashlab** [comment] 2018-10-11 11:43
oops, we missed one framework! please copy this one also ```Analytics/GoogleToolboxForMac.framework```

And also use this newer version of the ANE: [googleSignIn.ane.zip](https://github.com/myflashlab/GoogleSignIn-ANE/files/2468723/googleSignIn.ane.zip) This seems to be working fine now.

**Comment by myflashlab** [comment] 2018-10-11 11:43
Please confirm if the latest ANE fixes the problem for you too?

**Comment by Parkdaejoon** [comment] 2018-10-11 11:54
It took some time to test with App Store testflight. Yes, it works normally.^^ 
And is it correct to download the latest version of the course above ANELAB > ABOUT-> CHECK FOR UPDATE?

**Comment by myflashlab** [comment] 2018-10-11 12:03
Now V1.4.0 of the ANE is released through the ANELAB channel. It will take us a few days before we are able to release it manually through zip packages.

Thanks for helping us locate the bug and kill it 🙂

**Closed by myflashlab** 2018-10-11 12:03 UTC
Labels: bug

**Comment by Parkdaejoon** [comment] 2018-10-11 12:16
V1.4.0 I just downloaded and applied via ANELAB. This will be a DEMO indication, not a genuine article.

**Comment by myflashlab** [comment] 2018-10-11 12:20
The demo dialog will be removed only after you hit big blue button in ANELAB.

<img width="753" alt="screen shot 2018-10-11 at 4 19 56 pm" src="https://user-images.githubusercontent.com/1692948/46803632-9800fc00-cd71-11e8-8a3a-40c8e96ba5be.png">

**Comment by myflashlab** [comment] 2018-10-11 12:33
To use ANELAB:

1. always make sure you have the latest version of the ANEs and the software:
<img width="520" alt="screen shot 2018-10-11 at 4 26 47 pm" src="https://user-images.githubusercontent.com/1692948/46803964-7c4a2580-cd72-11e8-974d-51ee274b9780.png">
2. Set path to JAVA and AIR SDKs:
<img width="519" alt="screen shot 2018-10-11 at 4 27 32 pm" src="https://user-images.githubusercontent.com/1692948/46804014-a4d21f80-cd72-11e8-8e47-c459a272d3ea.png">
3. Then create a new project:
<img width="509" alt="screen shot 2018-10-11 at 4 25 10 pm" src="https://user-images.githubusercontent.com/1692948/46804031-b3b8d200-cd72-11e8-8027-2679e2d6dd17.png">
4. Enter the project details as seen on the page:
<img width="749" alt="screen shot 2018-10-11 at 4 25 38 pm" src="https://user-images.githubusercontent.com/1692948/46804052-c0d5c100-cd72-11e8-824b-9a12e254ff21.png">
5. Finally Start adding ANEs to your project easily and fast.
6. When finished, make sure your IDE is successfully implementing the added ANEs. ANELAB is not able to modify different IDEs for example, there's no way we can modify an .fla file!

**NOTICE:** To make sure you are not messing your settings, first create a backup, then delete from your manifest .xml file, the ```<android```, ```<ios``` and ```<extensions``` tags and also delete all the current ANEs available in your ```lib``` folder where you keep all the ANEs for your project. This way, the ANELAB software will install everything fresh on your project.

Spend some time playing with ANELAB, take your time. I'm sure you will find it very useful. it will save you a lot of time so you don't have to spend hours implementing ANEs. Good luck

**Comment by Parkdaejoon** [comment] 2018-10-11 12:35
Thank you for your kindness and explanation. I'll do as described above.^^

**Comment by Parkdaejoon** [comment] 2018-10-12 06:40
![ane](https://user-images.githubusercontent.com/31180282/46852169-0a86e000-ce35-11e8-80fb-7a423cb984df.png)
 << 

Continue to display as loading. If you apply the newly created "signin-V1.4.0.ane" file, you will also see a DEMO mark.

**Comment by myflashlab** [comment] 2018-10-12 06:49
After the ANE is added to your project, you must click on the [big wide blue button](https://github.com/myflashlab/GoogleSignIn-ANE/issues/19#issuecomment-428934260) that will remove the demo dialog for you. can you tell us why you can't pass this step?! let us know what problem you are facing and we'll help you more.

**Comment by Parkdaejoon** [comment] 2018-10-12 07:35
I don't know if I'm right when I did this. Please help me.
Videos below

http://sameboard.com/20181012_163022.mp4

**Comment by myflashlab** [comment] 2018-10-12 07:43
You mean the window "The ANE is being installed" never finishes?

1. have you downloaded all the ANEs from the update window?
2. in your computer's "documents" folder, possible error logs are saved in ```ANELAB_LOGS/logs.txt``` copy the content of that file here so we can see more.

**Comment by Parkdaejoon** [comment] 2018-10-12 07:49
1. Marking that it is being installed continues
2. I downloaded the update to 1.4.0
3. I can't find the log file.

Is it correct to proceed like a video?

**Comment by myflashlab** [comment] 2018-10-12 07:53
> I can't find the log file. just look into your computer's "documents" directory. If there's a crash in the software, there must be a log there at ```ANELAB_LOGS/logs.txt```!

By the way, make sure you are running the software with Admin permissions and make sure the firewall is not preventing operations of ANELAB.

**Comment by Parkdaejoon** [comment] 2018-10-12 08:03
log...

V1.1.25 - Fri Oct 12 07:19:15 2018 UTC
Error: TypeError: Error #1009
	at Main/globalErrorHandler()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::MidBody/onRerunSetup()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::ListItemAne/toRerunSetup()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.myflashlabs.tapale.button::ButtonBlock/onClick() 
V1.1.25 - Fri Oct 12 07:19:16 2018 UTC
Error: TypeError: Error #1009
	at Main/globalErrorHandler()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::MidBody/onRerunSetup()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::ListItemAne/toRerunSetup()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.myflashlabs.tapale.button::ButtonBlock/onClick() 
V1.1.25 - Fri Oct 12 07:19:18 2018 UTC
Error: TypeError: Error #1009
	at Main/globalErrorHandler()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::MidBody/onRerunSetup()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::ListItemAne/toRerunSetup()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.myflashlabs.tapale.button::ButtonBlock/onClick() 
V1.1.25 - Fri Oct 12 07:19:19 2018 UTC
Error: TypeError: Error #1009
	at Main/globalErrorHandler()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::MidBody/onRerunSetup()
	at flash.events::EventDispatcher/dispatchEvent()
	at win.project.aneAction::ListItemAne/toRerunSetup()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.myflashlabs.tapale.button::ButtonBlock/onClick() 
V1.1.25 - Fri Oct 12 07:20:55 2018 UTC
Error: Error: '"D:\java101/bin/"jar.exe'Àº(´Â) ³»ºÎ ¶ǴÂ ¿ܺÎ ¸í·É, ½ÇÇàÇÒ ¼ö ÀִÂ ÇÁ·α׷¥, ¶ǴÂ

¹èġ ÆÄÀÏÀÌ ¾ƴմϴÙ.


	at Main/globalErrorHandler() 
V1.1.25 - Fri Oct 12 07:27:00 2018 UTC
Error: Error: '"D:\java101/bin/"jar.exe'Àº(´Â) ³»ºÎ ¶ǴÂ ¿ܺÎ ¸í·É, ½ÇÇàÇÒ ¼ö ÀִÂ ÇÁ·α׷¥, ¶ǴÂ

¹èġ ÆÄÀÏÀÌ ¾ƴմϴÙ.


	at Main/globalErrorHandler() 
V1.1.25 - Fri Oct 12 07:31:14 2018 UTC
Error: Error: '"D:\java101/bin/"jar.exe'Àº(´Â) ³»ºÎ ¶ǴÂ ¿ܺÎ ¸í·É, ½ÇÇàÇÒ ¼ö ÀִÂ ÇÁ·α׷¥, ¶ǴÂ

¹èġ ÆÄÀÏÀÌ ¾ƴմϴÙ.


	at Main/globalErrorHandler()


You can't run as an administrator and it has nothing to do with firewalls.

**Comment by myflashlab** [comment] 2018-10-12 08:12
Ok, this seems like a JAVA problem but for some reason, we are not seeing the complete error log! it is unreadable. could you check what Java version do you have?

**Comment by myflashlab** [comment] 2018-10-12 08:17
Oh, and you do have JAVA **JDK** installed, right?

**Comment by Parkdaejoon** [comment] 2018-10-12 08:17
![java](https://user-images.githubusercontent.com/31180282/46856937-b256da80-ce42-11e8-8168-bef2e7c2d6f3.png)

**Comment by myflashlab** [comment] 2018-10-12 08:19
I can't read that obviously! but you need JDK https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by Parkdaejoon** [comment] 2018-10-12 08:34
new installation of jdk and modified path
The same symptoms are repeated.

log..

	at Main/globalErrorHandler() 
V1.1.25 - Fri Oct 12 08:27:31 2018 UTC
Error: Error: Error #1000
	at Main/globalErrorHandler() 
V1.1.25 - Fri Oct 12 08:28:52 2018 UTC
Error: Error: '"C:\Program Files\Java\jre1.8.0_181/bin/"jar.exe'Àº(´Â) ³»ºÎ ¶ǴÂ ¿ܺÎ ¸í·É, ½ÇÇàÇÒ ¼ö ÀִÂ ÇÁ·α׷¥, ¶ǴÂ

¹èġ ÆÄÀÏÀÌ ¾ƴմϴÙ.


	at Main/globalErrorHandler() 
V1.1.25 - Fri Oct 12 08:31:19 2018 UTC
Error: Error: Error #1000
	at Main/globalErrorHandler()

**Comment by myflashlab** [comment] 2018-10-12 08:36
:thinking: Why am i seeing **jre**? ```C:\Program Files\Java\jre1.8.0_181/bin/```? Are you sure you have installed JDK and not JRE?

**Comment by myflashlab** [comment] 2018-10-12 08:39
And besides, ```Error #1000``` means **The system is out of memory.**! I'm starting to ge so much confused with what could be happening on your computer!

**Comment by Parkdaejoon** [comment] 2018-10-12 08:44
I'll put it in order.
1. I did jdk first, but the same symptoms.. That is why I changed to Jre folder.
2. It seems to be a low memory message while the message is still being installed.
3. I've got an error message.

The ANE setup is completed but before you can compile your project, there are a few things you have to do manually which we explain below:

The following resource bundle has been copied to your "assets" directory and it is required for the iOS side of your app. You need to make sure it is packaged at the root of your application. NOTE: The "assets" directory is the folder which you picked when you were creating this ANE-LAB projetc.

GoogleSignIn.bundle


NOTE: If you have installed Firebase Invite ANE before, This bundle has been added to your assets folder already. Don't worry, both these ANEs are using an identical version of GoogleSignIn.bundle

**Comment by Parkdaejoon** [comment] 2018-10-12 08:46
![jdk](https://user-images.githubusercontent.com/31180282/46858650-b38a0680-ce46-11e8-9e36-a5cc41081757.png)

**Comment by myflashlab** [comment] 2018-10-12 08:49
If you are seeing this message **"The ANE setup is completed but before you can compile your project............"**, This is NOT an error message, it means that the ANE has been successfully installed!

It just tells you that on the iOS side, you must make sure the file ```GoogleSignIn.bundle``` is bundled with your .ipa file.

**Comment by Parkdaejoon** [comment] 2018-10-12 08:59
The name of the file that was completed is "signin-V1.40.ane," which was tested in Android, and also comes with a Demo mark.
I hope that Demo will be able to receive the "googlesignin.ane" file by e-mail in a hurry. This kept me from working all day.

**Comment by myflashlab** [comment] 2018-10-12 09:08
We certainly have "language communication problems" here! First you said the installation window is not finishing its job, then later you are showing that the ANE setup is completed! :confused:

Ok, if the ANE setup is completed, why don't you just hit that [big wide blue button](https://github.com/myflashlab/GoogleSignIn-ANE/issues/19#issuecomment-428934260) to automatically get rid of the dialog window?! That button will register the ANEs to your app and places a ```key``` to your manifest file and the demo dialog will be removed.

If you want to have access to the latest ANE via the classic .zip file download from your myflashlabs panel, you need to wait till Monday. It takes us time to prepare the classic .zip releases. That's why we have developed the ANELAB software to begin with. To speed things up.
